try:
    a = 1200 / 0
    # Passa a Exceção para a variavel erro e exibe
except Exception as erro:
    print('ERRO:', erro)